# Team Information
teams:
  one:
    name: "Team Blue"
    flag: null
  two:
    name: "Team Red"
    flag: null

# Win condition
flags_to_win: 5

# Time before a player respawns, in seconds. Does not support decimals.
respawn_timer: 5

# The block to be used as the flag. Must be a valid material, or it will default to IRON_BLOCK.
flag_type: GOLD_BLOCK
# The block that replaces the flag when taken by the enemy.
missing_flag_type: SMOOTH_STONE

# Pair players together who are standing very close to each other when making teams. (limited to groups of 2)
pair_nearby_players: true

# Force pairs to stick together, regardless of team imbalance.
# If true, max imbalance is 2. If false, max imbalance is 1. (I think)
# If pair_nearby_players is false, this won't do anything.
strict_pairing: false

# Number of seconds between item spawns. Keep in mind that ALL item spawners pop out items at the same time.
item_spawn_rate: 20

# Item Spawners
item_spawners: null