name: SootCTF
author: skyphi
version: 1.3.3
api-version: 1.20
main: dev.skyphi.SootCTF
depend: [ProtocolLib]
commands:
  sootctf:
    description: Main SootCTF command
    usage: /<command> <number>
    default: op
    aliases: [ctf]
  score:
    description: Get the current game's score
    usage: /<command>